### ISSUE TITLE
[Help] EBDB cannot load records from source.

### ISSUE THREAD

**Issue by fingerknight** [girzel/ebdb#108]
Hi, I have troubles using EBDB.

[QUESTION]

I've just test add one record and save it into EBDB. 

![2022-11-26_20-47-41](https://user-images.githubusercontent.com/56252828/204089862-5d48fdf5-aff9-4713-88c8-97470ba542c0.png)

![image](https://user-images.githubusercontent.com/56252828/204089878-ee21b6be-fe1b-472c-807c-fdc41c44e799.png)

Then I shut down Emacs and restart it. After entering the command `ebdb-open`, I got **nothing** in `*EBDB*` buffer.

![image](https://user-images.githubusercontent.com/56252828/204089953-ab38ebb5-6a62-4977-8e55-c1ad985c5b64.png)

[Configuration]

I've git clone the repository to local directory, and added it to `load-path`. Here is my configuration.

![image](https://user-images.githubusercontent.com/56252828/204090028-b7eac923-14e4-4846-a537-75bf38635be6.png)

I've try `(use-package ebdb)`, but i could not find `ebdb-open` command. Then I check the source code of EBDB, I just found it in `ebdb-com.el`, in which `ebdb` has been required.

Any suggestions?

**Comment by girzel** [comment]
As the docstring of `ebdb-open` says, it only opens a buffer, it doesn't do anything else: this isn't the main entry-point to EBDB. Typically an \*EBDB\* buffer will only show you what you've searched for, and `ebdb-open` doesn't initiate search. Either use `ebdb` as the main entry-point or, once you're already in a \*EBDB\* buffer, use the search commands (on the "/' prefix) or display all records (on "C-x n w", as analogous to `widen`).

If that answers your question, please go ahead and close this issue!

**Comment by fingerknight** [comment]
Oh, I see. It does work.

I had read the manual, but did not found I have to search to the records. BBDB works like that?

BTW, is that more reasonable to reqire `ebdb-com.el` inside `ebdb.el`?

Anyway, thanks for replying ;)

**Comment by girzel** [comment]
Yes, that's how BBDB works -- the `bbdb` command initiates search.

`ebdb.el` is meant to be standalone -- it shouldn't need to know anything about `ebdb-com.el`. All the commands in `ebdb-com.el` are autoloaded, so that library will get loaded as needed.
