### ISSUE TITLE
Suggest add a mode which is like bbdb-handy

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#18]
bbdb-handy (https://github.com/tumashu/bbdb-handy) is a tool, which pop up a BBDB window as email-address chooser. I use it daily and find it is a good mode, suggest add a similar tool to ebdb

**Comment by girzel** [comment]
Interesting! I'm not quite sure what advantages this would provide over company-ebdb.el, or other completion frameworks, though. Why do you need to pop up a buffer and see the whole contact?

(By the way, if you have time please try out ebdb-i18n and ebdb-chn, and let me know how the Chinese-specific behavior works for you. I'm planning on adding specific parsing/display functions for Chinese phone numbers and addresses, eventually. 多谢！)

**Comment by tumashu** [comment]
1. very simple and easy use
2. works well with any language, company use popup-el and show chinese ugly.
3. less dependence, company is too heavy for write mail

I will port my config from bbdb to ebdb when i have time

**Comment by tumashu** [comment]
关于这个功能，我也将当时的一些折腾经验说说，希望大家不要掉相同的坑，

其实使用bbdb等联系人管理软件，99%的时间都是用来补全联系人的，bbdb使用emacs内置的
补全机制，我当时想用pinyin补全，因为如果写汉字的话，就太麻烦了．但代码实在是搞不定，
根本就看不懂，后来有一天，我在折腾ebib的时候，发现一个ｃｉｔｅ推送功能，我机灵一动，
就搞出这个bbdb-handy了，一直用到现在，而且非常稳定，再加上可以多选，一次提交功能，
非常好用．

中间我也折腾过　company 补全，　company　使用　overlay 机制的　menu, 一遇到显示中文
的时候，就面目全非，我现在company都禁只补全中文．对helm本身无爱，估计是早期的时候
被坑怕了，更落下了　emacs 分屏管理靠人品的错觉，所以几乎不考虑helm，另外一个可以考虑
的就是　ivy，我觉得它的行为很稳定．　有个哥们写了一个 counsel-bbdb,　就是用ivy机制的．
不过所有这些东西，都依赖外部的包，没有bbdb-handy可控性高，添加一个bbdb-handy类似的
工具，作为默认补全工具，其实是很不错的选择．
