### ISSUE TITLE
Only highlight one email-address when have mulit email-address

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#20]
```
mail: a@gmail.com, b@qq.com, c@163.com
```
only c@163.com will be highlight or faced

**Comment by girzel** [comment]
Mail addresses are given a face based on their "priority". You can edit the priority by using "E" on the email address. Choose "primary" from the priority options.

Are you saying that more than one address has the "primary" priority? Eventually I would like to add checks that only allow one address to be primary at a time, but right now it's true you can make more than one address primary.

**Comment by tumashu** [comment]
```
Mail addresses are given a face based on their "priority". 
```
I know, thanks!
