### ISSUE TITLE
Suggest add a mark char when mark

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#30]
For example:
```
#测试
   phone: (work) 13313255xxx
```

**Comment by girzel** [comment]
Isn't the highlighting enough?

**Comment by tumashu** [comment]
Maybe the real issue is that the current highlighting looks too ugly in my opinion :-)

**Comment by girzel** [comment]
Ha! Well... I might get around to this. Pull requests welcome :)

**Comment by girzel** [comment]
Looks like I'm not going to get around to it!
