### ISSUE TITLE
A question about merge record

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#31]
When two record have same name, but it is not same person, How to deal with  record merge?

**Comment by girzel** [comment]
Each record has a UUID, this is the only field that is considered when merging.

This means that, when you have have multiple databases, you can have one record saved to more than one database. At load time they will be automatically merged. I don't have much confidence in this process yet, though I've been using it for a while -- I haven't really stress-tested it yet.

**Comment by tumashu** [comment]
How to generate UUID?

**Comment by girzel** [comment]
You don't! It happens automatically when you add a record to a database. But you can also use `ebdb-make-uuid`. Customize `ebdb-uuid-function` to change how that works.

**Comment by tumashu** [comment]
OK

**Comment by girzel** [comment]
Hit "T" on a record in the *EBDB* buffer to see the UUID. Also see `ebdb-record-self`.

Otherwise, I'll close this...

**Comment by tumashu** [comment]
OK
