### ISSUE TITLE
Is it possible set ~/.emacs.d/ebdb's coding?

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#35]

**Comment by tumashu** [comment]
![qq 20170223170609](https://cloud.githubusercontent.com/assets/67725/23252065/6a54d6f2-f9ea-11e6-9799-55058df79f03.png)

**Comment by girzel** [comment]
eieio-persistent-save can only write in utf-8-emacs. What coding system are you using? I guess I'll have to make sure everything gets converted correctly.

**Comment by tumashu** [comment]
utf-8 in linux and gbk in window

**Comment by tumashu** [comment]
maybe we should force add follow line to ebdb file, so user can proper open and view it
```
;; Local Variables:
;; coding: utf-8-unix
;; End:

```

**Comment by girzel** [comment]
The file is saved as utf-8, and Emacs should be able to recognize that and open it as utf-8. When you open the file, what coding system does it open the file in? Down at the bottom left of the mode line?

**Comment by tumashu** [comment]
gbk

**Comment by girzel** [comment]
I'd rather not monkey-patch the files...

Would you eval this snippet, and tell me if it works okay? If so, I'll add it to `ebdb-load`.

```elisp
(push
     (cons
      (regexp-opt (mapcar (lambda (db)
			    (slot-value db 'file))
			  ebdb-db-list))
      'utf-8-emacs)
     auto-coding-alist)
```

**Comment by tumashu** [comment]
tomorrow， I will try this :-)

**Comment by girzel** [comment]
Do let me know if this takes care of it!

**Comment by tumashu** [comment]
好像ebdb buffer不乱码了，但.ebdb还是不能正确识别为UTF-8

**Comment by girzel** [comment]
它应该就是把utf-8 decode 为 gbk，这没有问题。如果 *EBDB* buffers 可以正常输入、显示内容，就差不多了。

**Comment by tumashu** [comment]
OK

**Comment by fu123456** [comment]
ebdb default file is ~/.emacs.d/ebdb, but I want to define other directory, for example ~/MEGA/ebdb.gpg.
I set {{(setq ebdb-file "~/.emacs.d/ebdb.pgp")}},
but it does not work. How to solve it?

**Comment by girzel** [comment]
You should just be able to:

``(setq ebdb-sources (list "~/.emacs.d/ebdb.pgp"))``
