### ISSUE TITLE
Dial VOIP Phone from ebdb

### ISSUE THREAD

**Issue by ddoherty03** [girzel/ebdb#37]
And here's another wish.  The old bbdb used to have the ability to dial an old land-line phone (I think with M-d).  I would really like to be able to point at a record (or phone field) in ebdb and dial it, maybe have the phone go on speaker, and optionally, pop up an org capture window for taking notes.

And what about detecting incoming calls the way incoming emails are now and capturing caller-id info for a potential new ebdb record.

Was I asleep?  I'm sorry, I must have been dreaming. :)

**Comment by girzel** [comment]
Whoa there! One thing at a time. As far as I know, BBDB gave you the option of specifying a function for dialing numbers (EBDB provides the same option), but didn't actually come with one. If you didn't provide a function, it just punted to:

```
(browse-url (concat "tel:" phone-string))
```

Is anything actually registered to handle that on your system? It would be trivial to re-instate the `browse-url` call, but providing a function that actually went out and dialed a number somehow would require some research.

A minute of Googling turned up Twinkle and sipcmd, and maybe a way to tap into Skype – do you use any of those?

Anyway, let me know what you think might work, and I'll see what I can do. As for turning EBDB into a full-blown call center... that might take a while yet.

**Comment by girzel** [comment]
Holy crap Signal has a command line client. I'll look into this...

**Comment by ddoherty03** [comment]
Go, @girzel, Go!  This would be awesome!

**Comment by ddoherty03** [comment]
I honestly don't know much about the whole sip/voip/asterisk world.  I would just like to be able to dial my desktop Cisco voip phone from emacs.  I see [linphone.org](http://www.linphone.org/l) has a command line client, but I'm not sure it can hook into an abitrary phone or just theirs.  Also I see [pjsip](http://www.pjsip.org/pjsua.htm#cmd_call) which also looks interesting.  Cisco also has something, but I don't see that it has commands fro just dialing the dang thing.  [Cisco](http://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cucm/cli_ref/8_6_1/cli_ref_861.html).

Would be nice if a sip/voip expert did some kind of emacs library for basic phone functions.  I get lost in all this stuff.

**Comment by girzel** [comment]
This is a bit anticlimactic: it only gives you the ability to send text messages via Signal; you have to do all the hard work of setting up signal-cli in advance. I'll admit I haven't successfully set that up yet, despite trying on no less than three computers, so this patch is largely theoretical, though I have proved via Science that it will work.

Signal-cli also provides the ability to receive text messages for an account, but all that is getting beyond the scope of EBDB -- there should be a separate package for handling Signal conversations.

**Comment by tumashu** [comment]
adb shell service call phone 2 s16 "10086"

**Comment by girzel** [comment]
What do I have to check for to make sure this is available? Is (executable-find "adb") sufficient?

**Comment by tumashu** [comment]
```
What do I have to check for to make sure this is available? Is (executable-find "adb") sufficient?
```
In linux, this may work, in windows, I don't know

**Comment by girzel** [comment]
I'm closing this, I think the right thing is just to register a handler for the "tel:" URI on your system, as of 3210ad793cd8a418328e7093dc055c1ab1416bf9, the phone string URI is passed correctly to `browse-url`.
