### ISSUE TITLE
I can't let ebdb-search-transform-functions work

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#39]
```
(defun eh-ebdb-search-chinese (string)
  (if (functionp 'pyim-isearch-build-search-regexp)
      (pyim-isearch-build-search-regexp string)
    string))

(setq ebdb-search-transform-functions
      '(eh-ebdb-search-chinese))


```

**Comment by girzel** [comment]
Would you see if that fixes it?

**Comment by tumashu** [comment]
I can search chinese when I call ebdb command,  but ebdb-complete can not work again, ebdb-complete use the following sexp:

```
(ebdb (ebdb-search-style) "fs")
```

**Comment by girzel** [comment]
Okay, I think this should fix it once and for all!

**Comment by girzel** [comment]
Also, I've been looking into character folding in searches, and am adding that as an option in searching. Check out the variable `char-fold-table`. It's possible we could just add Chinese character folding to this table, though I don't know how feasible that would be.

**Comment by tumashu** [comment]
make search feature powful is a good job.
