### ISSUE TITLE
had to set bbdb-file to upgrade

### ISSUE THREAD

**Issue by tromey** [girzel/ebdb#50]
The upgrade instructions did not work as-is for me.  I investigated and in `ebdb-migrate-from-bbdb` I see that it expects `bbdb-file` to be set.  I have never set this, though -- it is set by BBDB.  Perhaps the migration code should know about the default setting for this.

**Comment by girzel** [comment]
Ah, I'd originally had more explicit upgrade instructions in the README, but the manual came out a bit more terse. I'll expand the manual, and also check for BBDB file at the default location. Thanks for the report.
