### ISSUE TITLE
ebdb-reload-database doesnt seem to work

### ISSUE THREAD

**Issue by jave** [girzel/ebdb#57]
at least not according to how i expect it to work.

I had some problems in my ebdb file i fixed manually, mostly pnone numbers with random strings in them, artifacts from migrations. I removed the strings from the phone numbers in the phone fields, and did ebdb-reload-database. but the old database wasnt purged. In the end i restarted emacs and my changes was installedd then.

**Comment by girzel** [comment]
You manually fixed the strings in the database file, right? I just tried this and it worked correctly:

1. Load EBDB
2. Open the EBDB database file and change someone's email address
3. Go back to the EBDB buffer and use "d r" to reload the database
4. The email address changed in the EBDB buffer

Is that what you were doing? What happened differently?

**Comment by jave** [comment]
okay, I cant reproduce the problem now.

the problem was that a name that i had removed from the db file was still in memory, but now i cant reproduce.
