### ISSUE TITLE
eieio form like editing of contact?

### ISSUE THREAD

**Issue by jave** [girzel/ebdb#59]
It would be nice if the eieio form editor could be used to edit a contact

**Comment by girzel** [comment]
It can! Mostly. Try hitting "E" on a field. Most fields can be edited this way.

**Comment by jave** [comment]
wow! I guess i should rtfm :) odd thing though, when i did an elpa install, the info file seemingly didnt get installed for some reason, at least not properly in the info index

**Comment by girzel** [comment]
Hmm, that was a problem early on (see #49), but that should be solved now. Isn't there a "dir" file in the package?

**Comment by jave** [comment]
I reinstalled ebdb and the dir file is there now, thanks!
