### ISSUE TITLE
Issues with packages in elpa and keys

### ISSUE THREAD

**Issue by schvabodka-man** [girzel/ebdb#65]
Hi, i'm trying to install any ebdb-releated package from elpa and getting this:

Failed to verify signature seq-2.20.tar.sig:
No public key for 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org> created at 2017-05-05T00:05:02+0300 using DSA
Command output:
gpg: keyblock resource '/tmp/try28880WQE/gnupg/pubring.kbx': No such file or directory
gpg: Signature made пт, 05-тра-2017 00:05:02 +0300 EEST
gpg:                using DSA key 474F05837FBDEF9B
gpg: Can't check signature: No public key

This error is not present while isntalling any other package from elpa or installing ebdb from github using el-get

**Comment by girzel** [comment]
Looks like that error is coming from installing the seq package, which is one of EBDB's dependencies. I'll take a look tomorrow.

**Comment by girzel** [comment]
I haven't been able to reproduce this, and looking at your error message I'm not sure why it would be looking for your public keyring under the "/tmp" directory. Does the problem persist after restart? If so,  I would raise this on the emacs-devel mailing list.

**Comment by girzel** [comment]
One more question: can you give me your Emacs version and OS? Thanks

**Comment by schvabodka-man** [comment]
Os - minimal Ubuntu 17.10
Emacs - 25. Recent version from repos

**Comment by girzel** [comment]
Well, I don't know what to tell you. I brought this up on emacs.devel, and got a shrug. Your elpa keyring is supposed to be at the location pointed to by package-gnupghome-dir, which for me is "~/.emacs.d/elpa/gnupg". Maybe you've got that set incorrectly somehow?

Either way, it's not a problem with EBDB, and probably not something I can solve...
