### ISSUE TITLE
Importing vcard from Android 7.0

### ISSUE THREAD

**Issue by DrWaleedAYousef** [girzel/ebdb#66]
I export my contacts from Android 7.0; it seems that it uses vcard 4.0 (not sure). Anyway, EBDB is not able to import from the vcard file! Any help?

Thanks so much.

**Comment by girzel** [comment]
Coincidentally, I started working on that just today -- it will be part
of EBDB, but require the parsec package. It might take a me a few weeks
to get it finished, though...

**Comment by girzel** [comment]
Duplicate of #2 
Duplicate of #60
