### ISSUE TITLE
`seq` required, no `seq-sort-by`

### ISSUE THREAD

**Issue by swflint** [girzel/ebdb#67]
I have Emacs 25.3.1, `seq` 2.3.  `seq-sort-by` does not exist.

**Comment by girzel** [comment]
Bother -- that hadn't occurred to me. You must be running EBDB from git,
right? I'll drop the use of that (though it was very handy) and figure
out which version of seq includes seq-sort-by.

Thanks for the report.

**Comment by girzel** [comment]
Oh... EBDB has a Package-Requires with (seq "2.15"), which does include `seq-sort-by'. The Elpa repo has seq 2.20 available. I think if you'd installed EBDB through the package manager, it would have brought down seq 2.20 as well, as a dependency.

I encourage people to run EBDB from git, as I get early-warning bug reports, but I think if you do that you'll have to handle the dependencies yourself, by installing a newer version of seq from the repos.

**Comment by swflint** [comment]
I am running from git, and I'll take a look in elpa.  It does appear that more recent versions of `seq` may have removed `seq-sort-by`.

**Comment by girzel** [comment]
Pretty sure seq 2.20 has `seq-sort-by` in it -- try installing that?

**Comment by swflint** [comment]
That's still a version previous to what I have.  Either way, where would I find said previous version?

**Comment by girzel** [comment]
No, Elpa uses a semver-style versioning scheme, meaning that 2.20 is greater than 2.3. If you use the GNU package repository, meaning that your `package-archives` contains `("gnu" . "https://elpa.gnu.org/packages/")`, then you should be able to find seq 2.20 there.

**Comment by swflint** [comment]
I did update it and I'm still getting the error.

**Comment by girzel** [comment]
I'm not sure what to tell you... After installation, in the directory pointed to by `package-user-dir`, there should be a directory called "seq-2.20", and the contents of that should look like: https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=tree;f=packages/seq

If you're using Emacs 25, loading seq.el should load seq-25.el, which contains `seq-sort-by`.

Does any of that seem wrong?

**Comment by swflint** [comment]
Go figure.  Sadly, it still doesn't work.

**Comment by girzel** [comment]
Last ditch question, before I give up and replace the call to `seq-sort-by`: what do you get for `(locate-library 'seq)` and `(locate-library 'seq-25)`?

Thanks...

**Comment by swflint** [comment]
Turns out I had installed it previously and forgotten about it.  Sorry for the waste of time.

**Comment by girzel** [comment]
Glad it got sorted!
