### ISSUE TITLE
problem on upgrade to 0.5.4

### ISSUE THREAD

**Issue by gmcninch** [girzel/ebdb#71]
I just upgraded ebdb to 0.5.4 via emacs package manager. I then restarted emacs, and started gnus. Now if I try to compose a message (e.g. "m" from the group buffer), I get an error:

> `custom-initialize-reset: Invalid slot name: "#<ebdb-field-role ebdb-field-role-16c7aa4>", object-name`

I'm not entirely sure why message/ebdb is looking at field-roles at this stage, but I note that I get the same sort of error if I enter a (partial) mail recipient in the "To:" field and press `<tab>`.

This problem doesn't occur with 0.5.3 (but since no one else has reported this, it makes me wonder if there isn't something flaky about my contacts data?).

-george

**Comment by gmcninch** [comment]
Hi, thanks for the reply. Actually, the problem seems to have been *my* fault. I had written some "defmethods" for display of ebdb fields. I just commented that code out, restarted, and everything worked. I had "ruled that out" earlier, because I didn't think those methods would have been called. But I was evidently wrong...!

Looking more carefully, I had code for 

> `(cl-defmethod ebdb-fmt-field ((_fmt ebdb-formatter)
>      			      (field ebdb-field-address)
>      			      (_style (eql collapse))
>      			      (_record ebdb-record))  ...`

and

> `(cl-defmethod ebdb-fmt-field ((fmt ebdb-formatter-ebdb)
> 			      (field ebdb-field-role)
> 			      _style
> 			      (record ebdb-record-person))`

and I think that the point of my code was to include "multi-line" address information in the ebdb display.

I do note that at least the second of my defmethod's  refers explicitly to

> `(slot-value field 'object-name)`

Maybe it'll "just work" if I change that to 'label instead? I'll give it a shot...

Anyhow, sorry for the noise!

**Comment by girzel** [comment]
Excellent! Glad that wasn't my fault :) No guarantees about code structure stability until 1.0!

But I am glad that people are playing with this level of display code. It's an area that is still in flux. Do let me know if you have any requests/comments/confusions/ideas.
