### ISSUE TITLE
csv-mode dependency

### ISSUE THREAD

**Issue by aminb** [girzel/ebdb#72]
Hi,

Upon updating my packages today I noticed that EBDB’s latest `master`
now implicitly depends on `csv-mode` from GNU ELPA.

It’d be great if the dependency were made explicit, and preferably
optional.

Thanks,

**Comment by girzel** [comment]
Oh weird, I was totally sure that csv-mode was built in. I'll make that optional.

**Comment by girzel** [comment]
When you have a moment, would you pull and check again? 65247f6daa9b0a331f70b81262193787e1a55ad8 should fix this.
