### ISSUE TITLE
How to disable pop in GNUS when open message

### ISSUE THREAD

**Issue by vutuan9182** [girzel/ebdb#74]
Hi, 
The first, thanks for great package.

But, I don't want show the ebdb buffer when I am reading email. Could I disable that, I search in customization group but I cant find them.

Could you help me?

**Comment by girzel** [comment]
Hmm, setting `ebdb-mua-pop-up` to nil is supposed to fix this. But something tells me that Gnus might open an empty window even if that option is nil.

Would you set that to nil and tell me if it fixes the problem?

**Comment by vutuan9182** [comment]
You predict right, Gnus totally open an empty window. Will you fix it?

**Comment by girzel** [comment]
I think that d9fc7e0 should do it, would you please try that patch?

**Comment by girzel** [comment]
This fix will be available in version 0.6.4. I think it should do the trick and will close this report, but feel free to re-open it if something still behaving strangely.

**Comment by vutuan9182** [comment]
Thank you very much. It work well now.
