### ISSUE TITLE
Should the "format test" buffer get cleaned up, or???

### ISSUE THREAD

**Issue by hartzell** [girzel/ebdb#79]
I just noticed that I had an unexpected buffer hanging around, named "format test".  It's clearly EBDB output, and a quick ripgrep showed me that it's created on [line 742 of ebdb-com.el]( https://github.com/girzel/ebdb/blob/master/ebdb-com.el#L742).

Is it something that you "should" be cleaning up, or???

**Comment by girzel** [comment]
Huh, I wonder why I was doing that. At first glance I don't see any reason that shouldn't be a `with-temp-buffer`, I will stare at it a bit longer and fix if I can't figure it out. Thanks.
