### ISSUE TITLE
How should I enable VM support?

### ISSUE THREAD

**Issue by hartzell** [girzel/ebdb#80]
The manual sez this in the [MUA section](https://github.com/girzel/ebdb/blob/master/ebdb.org#loading-mua-code)

> MUAs supported by EBDB include gnus, message, mh-e, mu4e, wl, and rmail.

I'm a VM user (not the last, I think, but...), and I see a handful of references to VM in the code.

But, its not clear how much support is there, if it works, or how to enable it.

**Comment by girzel** [comment]
You're hitting all the bugs! I think there was originally a bbdb-vm.el file that I copied over to ebdb-vm.el, but eventually deleted because I couldn't find anyone using VM and wasn't sure what was required for integration. Hang on while I find a copy of VM to test with, and I'll put support back in.

**Comment by hartzell** [comment]
> You're hitting all the bugs! [...]

We all have our special skills....

I can share my `straight.el` config w/ you, but it's a bit complicated because vm expects to have `autoconf`, `configure` and `make` run on it, which isn't `straight.el`'s happy path.

And, you can count on me to give it a test run.  ;)

**Comment by hartzell** [comment]
In fact, I ended up forking and working from a slightly older commit, then layering a commit of my own with two known fixes on it.

Here's what I'm running: https://github.com/hartzell/vm/tree/oldie

**Comment by girzel** [comment]
Excellent, I'll try it using that version of VM. And it turns out that there's a "vm-mua" branch here with EBDB' VM code already in it, so obviously I meant to do this and then forgot about it. Don't bother running that yet, let me just do some basic sanity tests first.

**Comment by girzel** [comment]
If you can't tell which library you're using, maybe it doesn't matter :)

Anyway, I'm going to close this report since I think the basic issue is resolved: ebdb-vm.el is present. If you hit more specific bugs, open more reports!
