### ISSUE TITLE
Adding a phone number prevents display

### ISSUE THREAD

**Issue by swflint** [girzel/ebdb#81]
Adding a phone number, e.g., using "i phone USA", prevents proper display upon completion (it appears it doesn't separate out the area code).  To get display to work correctly, I need to save the file, close emacs, edit the entries, and then start emacs again.

**Comment by girzel** [comment]
Huh, that's odd. I'll assume two things: you've loaded `ebdb-i18n.el`, and you are entering the phone number as a singe undifferentiated string of digits. Is that right?

There should be an `ebdb-parse` method for USA phone numbers that will always get this right, but apparently I haven't written that yet! In the meantime, you should be able to get correct behavior by leaving a space (or a hyphen or a dot or really anything else) between the area code and the rest of the number.

I'll add a new method to fix this.

**Comment by swflint** [comment]
That is correct.  Will do for the time being.
