### ISSUE TITLE
notmuch support

### ISSUE THREAD

**Issue by brabalan** [girzel/ebdb#84]
I can complete addresses using ebdb when I do `notmuch-compose`, but I don't know how to add an address (`ebdb-mua-update-records` does not work in `notmuch-show` mode). I tried using `ebdb` manually to search for the record and add an email address, but I can only edit existing addresses, not add new ones. Is there a workaround to use ebdb with notmuch?

**Comment by girzel** [comment]
There's no support simply because I haven't gone and written it! Which is odd since notmuch is one of the more popular MUAs. I am drowning in work right now, but I will try to do this this weekend. Thanks for the reminder.

**Comment by brabalan** [comment]
Thank you for the great work!

**Comment by girzel** [comment]
I've just added the basics of a ebdb-notmuch.el library, would you try running that? It currently doesn't handle automatic pop-up and deletion of the EBDB buffer, but it does put the keymap under the ";" key, and adding records and stuff should work.

If you have any comments/problems let me know, meanwhile I'll work on supporting the pop-up end of things.

**Comment by brabalan** [comment]
Thanks a lot. I copied to new file to my configuration and it seems to work well.

**Comment by brabalan** [comment]
I thought this was released on ELPA but I get an error when calling `ebdb-mua-update-records`: `ebdb-get-address-components: EBDB does not support notmuch-show-mode`. Do you know when you will release it?

**Comment by girzel** [comment]
Hmm, it should definitely work in `notmuch-show-mode' -- are you sure
you're requiring 'ebdb-notmuch?

**Comment by brabalan** [comment]
Sorry, this was it. Thank you for the hint. As it's integrated I'll close this issue.
