### ISSUE TITLE
Confusion about relationship bidirectionality

### ISSUE THREAD

**Issue by DerBeutlin** [girzel/ebdb#86]
I'm a bit confused about the relationship field. When creating it it asks me for a "reverse label (for the other record)" (I assume that's supposed to be the label that is added in the entry of the other person linking to the current entry) and another label (which I suppose is the label for the current record linking to the other). However only the latter one is true the other entry does not get a label linking to the current entry.

**Comment by girzel** [comment]
Yes! Somewhere around here I've got this feature mostly worked out, using a hash-table to do the reverse relationship lookups, but I got distracted before actually finishing it and committing. Thanks for the push...

**Comment by girzel** [comment]
Okay, this is done, and I'll push it directly with a quiet version bump. Once the package updates please give it a test run and close this if it works as expected.

In general, I'm not super happy with the UI for relations and for roles. Would there be any point to a command that displayed a person's entire family, for instance? Anyway, if you have any thoughts or feature requests in that direction, feel free to let me know.

**Comment by DerBeutlin** [comment]
Works super fine, thanks for the fast response. I guess I will approach you with feature requests as soon as I'm more familiar with ebdb, but it definitely already skyrocketed my contact management..
