### ISSUE TITLE
cl-no-applicable-method: No applicable method: ebdb-field-readable-name

### ISSUE THREAD

**Issue by brabalan** [girzel/ebdb#90]
After upgrading ebdb, I get this when I try to send a message:
```
cl-no-applicable-method: No applicable method: ebdb-field-readable-name, #s(ebdb-field-mail nil "***@***" primary) 
```

I'm using ebdb with notmuch.

How can I get around this?

**Comment by girzel** [comment]
On 05/19/20 06:01 AM, Alan Schmitt wrote:
> After upgrading ebdb, I get this when I try to send a message:
> ```
> cl-no-applicable-method: No applicable method:
> ebdb-field-readable-name, #s(ebdb-field-mail nil "***@***" primary)
> ```
>
> I'm using ebdb with notmuch.
>
> How can I get around this?

Can you send me the full traceback (use M-x toggle-debug-on-error
first)? Mail fields definitely work with `ebdb-field-readable-name', so
I'm not sure what's going on there.

Have you restarted Emacs since updating EBDB?

**Comment by brabalan** [comment]
I turned on debugging and I can no longer reproduce this. I had restarted emacs.

I will close this for the moment, and reopen if I can make it happen again. Sorry for the noise.
