### ISSUE TITLE
Stuck in a loop when creating a new person record.

### ISSUE THREAD

**Issue by mohkale** [girzel/ebdb#99]
I seem to be stuck in a loop when entering a new record, where it keeps pressing me for the address.

## Reproduction Instructions
1. Start emacs and load ebdb with ebdb-sources setup.
2. Run `M-x ebdb-create-record`.
3. Enter name, email, number. When at the first address prompt hit `C-g` to abort repeatedly. After aborting the address-label prompt I'm sent back to the street prompt. Interestingly the number for the street is still 1.

**Note**: I reverted back to `b08a5264ef2609b5cc789dcfe9452b02db384f0f` and am no longer seing this issue so it was probably introduced in the last 3 weeks.

**Comment by kimim** [comment]
i have this problem with recent elpa version 0.8.6

**Comment by girzel** [comment]
Yes, you'll need to update the package, the most recent version containing the fix is 0.8.7. There's still a little problem with entering empty strings vs C-g, but that will be fixed in the next release.

**Comment by kimim** [comment]
Thanks. But 0.8.7 is not available on elpa now.

**Comment by girzel** [comment]
No, only 0.8.8 :)
